# Development overrides for docker-compose
# This file is automatically loaded by docker-compose
version: '3.8'

services:
  atlas-api:
    environment:
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      - ./src:/app/src  # Mount source code for hot reload
    command: ["uv", "run", "uvicorn", "atlas_atc.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  atlas-dashboard:
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - ./src:/app/src  # Mount source code for hot reload