# docker-compose.override.yml - Local development overrides
# This file is automatically loaded by docker-compose and overrides settings in docker-compose.yml

services:
  # For local development, we don't need to specify platforms
  # Docker will automatically use the current platform
  atlas-api:
    build:
      context: .
      dockerfile: Dockerfile
      # Remove platforms specification for local builds
      # platforms setting is inherited from docker-compose.yml but can be overridden
    # Mount source code for hot reloading during development
    volumes:
      - ./src:/app/src:ro
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    # Enable hot reloading
    command: ["uvicorn", "atlas_atc.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  atlas-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./src:/app/src:ro
      - ./results:/app/results