# Prometheus configuration for ATLAS monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'atlas-monitor'

scrape_configs:
  # ATLAS API metrics
  - job_name: 'atlas-api'
    static_configs:
      - targets: ['atlas-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL exporter (if deployed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis exporter (if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

# Alerting rules (if needed)
rule_files:
  # - 'alerts/*.yml'

# Remote write configuration (optional)
# remote_write:
#   - url: 'http://remote-prometheus:9090/api/v1/write'